// Data examples pulled from https://github.com/dariusk/corpora
window['animals'] = [
  {
    name: 'agouti',
    collateral_adjectives: ['dasyproctid', 'dasyproctine'],
  },
  {
    name: 'amphibian',
    collateral_adjectives: ['amphibian'],
  },
  {
    name: 'ant',
    collateral_adjectives: ['formic', 'formicarian', 'formicid'],
  },
  {
    name: 'ant-eater',
    collateral_adjectives: ['myrmecophagous'],
  },
  {
    name: 'antelope',
    collateral_adjectives: ['antilopine'],
  },
  {
    name: 'ape',
    collateral_adjectives: ['apish', 'simian'],
  },
  {
    name: 'ass',
    collateral_adjectives: ['asinine'],
  },
  {
    name: 'badger',
    collateral_adjectives: ['meline'],
  },
  {
    name: 'bat',
    collateral_adjectives: ['cheiropterous'],
  },
  {
    name: 'bear',
    collateral_adjectives: ['bearish', 'ursine'],
  },
  {
    name: 'bee',
    collateral_adjectives: ['apian'],
  },
  {
    name: 'beetle',
    collateral_adjectives: ['coleopterous'],
  },
  {
    name: 'bird',
    collateral_adjectives: ['avian', 'avine', 'ornithic', 'volucrine'],
  },
  {
    name: 'bird of prey',
    collateral_adjectives: ['raptorial'],
  },
  {
    name: 'bug',
    collateral_adjectives: ['hemipteral', 'hemipteran', 'hemipterous'],
  },
  {
    name: 'butterfly',
    collateral_adjectives: ['lepidopterous', 'papilionaceous'],
  },
  {
    name: 'camel',
    collateral_adjectives: ['cameline'],
  },
  {
    name: 'capuchin monkey',
    collateral_adjectives: ['cebine'],
  },
  {
    name: 'carnivore',
    collateral_adjectives: ['carnivorous'],
  },
  {
    name: 'carp',
    collateral_adjectives: ['cyprine'],
  },
  {
    name: 'cat',
    collateral_adjectives: ['catty', 'feline', 'kittenish'],
  },
  {
    name: 'chicken',
    collateral_adjectives: ['gallinaceous', 'galline'],
  },
  {
    name: 'civet',
    collateral_adjectives: ['viverrine'],
  },
  {
    name: 'cod',
    collateral_adjectives: ['gadoid', 'gadine'],
  },
  {
    name: 'crane-fly',
    collateral_adjectives: ['tipulid'],
  },
  {
    name: 'cricket',
    collateral_adjectives: ['crickety'],
  },
  {
    name: 'crocodile',
    collateral_adjectives: ['crocodilian'],
  },
  {
    name: 'crow',
    collateral_adjectives: ['corvine'],
  },
  {
    name: 'crustacean',
    collateral_adjectives: ['crustacean'],
  },
  {
    name: 'deer',
    collateral_adjectives: ['cervine', 'rucervine'],
  },
  {
    name: 'dinosaur',
    collateral_adjectives: ['dinosaurian'],
  },
  {
    name: 'dog',
    collateral_adjectives: ['canine', 'doggish'],
  },
  {
    name: 'dolphin',
    collateral_adjectives: ['cetacean'],
  },
  {
    name: 'dove',
    collateral_adjectives: ['columbine'],
  },
  {
    name: 'duck',
    collateral_adjectives: ['anatine'],
  },
  {
    name: 'eagle',
    collateral_adjectives: ['aquiline'],
  },
  {
    name: 'earthworm',
    collateral_adjectives: ['lumbricine'],
  },
  {
    name: 'elephant',
    collateral_adjectives: ['elephantine'],
  },
  {
    name: 'elk',
    collateral_adjectives: ['alcine'],
  },
  {
    name: 'falcon',
    collateral_adjectives: ['falconine'],
  },
  {
    name: 'fish',
    collateral_adjectives: ['fishy', 'ichthyic', 'piscine'],
  },
  {
    name: 'flea',
    collateral_adjectives: ['pulicine'],
  },
  {
    name: 'fly',
    collateral_adjectives: ['dipteran', 'dipterous', 'muscid'],
  },
  {
    name: 'flycatcher',
    collateral_adjectives: ['muscicapine'],
  },
  {
    name: 'flying fox',
    collateral_adjectives: ['pteropine'],
  },
  {
    name: 'fowl',
    collateral_adjectives: ['gallinaceous', 'galline'],
  },
  {
    name: 'fox',
    collateral_adjectives: ['foxy', 'vulpine'],
  },
  {
    name: 'frog',
    collateral_adjectives: ['froggy', 'ranarian', 'ranid'],
  },
  {
    name: 'gadfly',
    collateral_adjectives: ['tabanid'],
  },
  {
    name: 'giraffe',
    collateral_adjectives: ['giraffine'],
  },
  {
    name: 'goat',
    collateral_adjectives: ['caprine', 'goatish', 'goaty', 'hircine'],
  },
  {
    name: 'goose',
    collateral_adjectives: ['anserine', 'goosy'],
  },
  {
    name: 'grasshopper',
    collateral_adjectives: ['acridian'],
  },
  {
    name: 'grouse',
    collateral_adjectives: ['tetraonid', 'tetraonine'],
  },
  {
    name: 'gull',
    collateral_adjectives: ['laridine'],
  },
  {
    name: 'hare',
    collateral_adjectives: ['leporine'],
  },
  {
    name: 'hawk',
    collateral_adjectives: ['falconine'],
  },
  {
    name: 'hedgehog',
    collateral_adjectives: ['erinaceous'],
  },
  {
    name: 'herbivore',
    collateral_adjectives: ['herbivorous'],
  },
  {
    name: 'herring',
    collateral_adjectives: ['clupean'],
  },
  {
    name: 'hippopotamus',
    collateral_adjectives: ['hippopotamian', 'hippopotamic', 'hippopotamine'],
  },
  {
    name: 'horse',
    collateral_adjectives: ['equine', 'horsy'],
  },
  {
    name: 'human',
    collateral_adjectives: ['hominid', 'human'],
  },
  {
    name: 'hyena',
    collateral_adjectives: ['hyenic', 'hyenine', 'hyenish'],
  },
  {
    name: 'hyrax',
    collateral_adjectives: ['hyracine'],
  },
  {
    name: 'iguana',
    collateral_adjectives: ['ignuanian', 'iguanid'],
  },
  {
    name: 'insect',
    collateral_adjectives: ['insectan'],
  },
  {
    name: 'jay',
    collateral_adjectives: ['garruline'],
  },
  {
    name: 'kangaroo',
    collateral_adjectives: ['macropine'],
  },
  {
    name: 'kite',
    collateral_adjectives: ['milvine'],
  },
  {
    name: 'leech',
    collateral_adjectives: ['hirudinal'],
  },
  {
    name: 'lemming',
    collateral_adjectives: ['microtine'],
  },
  {
    name: 'lemur',
    collateral_adjectives: ['lemurian'],
  },
  {
    name: 'limpet',
    collateral_adjectives: ['patelline'],
  },
  {
    name: 'lion',
    collateral_adjectives: ['leonine', 'lionish'],
  },
  {
    name: 'lizard',
    collateral_adjectives: ['lacertian', 'lacertine', 'saurian'],
  },
  {
    name: 'lobster',
    collateral_adjectives: ['homarine'],
  },
  {
    name: 'locust',
    collateral_adjectives: ['acridian', 'locustal', 'locustian', 'locustical'],
  },
  {
    name: 'louse',
    collateral_adjectives: ['pedicular', 'pediculine'],
  },
  {
    name: 'mackerel',
    collateral_adjectives: ['scombroid'],
  },
  {
    name: 'magpie',
    collateral_adjectives: ['garruline'],
  },
  {
    name: 'mammal',
    collateral_adjectives: ['mammalian'],
  },
  {
    name: 'marsupial',
    collateral_adjectives: ['marsupial'],
  },
  {
    name: 'marten',
    collateral_adjectives: ['musteline'],
  },
  {
    name: 'mite',
    collateral_adjectives: ['acarian', 'acarid', 'acaridan', 'acarine'],
  },
  {
    name: 'moa',
    collateral_adjectives: ['dinornithine'],
  },
  {
    name: 'mole',
    collateral_adjectives: ['moley', 'talpine'],
  },
  {
    name: 'mollusc',
    collateral_adjectives: ['molluscan', 'molluscous'],
  },
  {
    name: 'monitor',
    collateral_adjectives: ['varanian', 'varanid'],
  },
  {
    name: 'moth',
    collateral_adjectives: ['lepidopterous', 'tineid'],
  },
  {
    name: 'mouse',
    collateral_adjectives: ['mousy', 'murine'],
  },
  {
    name: 'mullet',
    collateral_adjectives: ['mugiloid'],
  },
  {
    name: 'mussel',
    collateral_adjectives: ['mytiloid'],
  },
  {
    name: 'octopus',
    collateral_adjectives: ['octopean', 'octopian', 'octopic', 'octopine'],
  },
  {
    name: 'oryx',
    collateral_adjectives: ['orygine'],
  },
  {
    name: 'osprey',
    collateral_adjectives: ['pandionine'],
  },
  {
    name: 'ostrich',
    collateral_adjectives: ['struthioid', 'struthionine', 'struthious'],
  },
  {
    name: 'otter',
    collateral_adjectives: ['lutrine'],
  },
  {
    name: 'owl',
    collateral_adjectives: ['owlish', 'owly', 'strigine'],
  },
  {
    name: 'ox',
    collateral_adjectives: ['bovine', 'taurine'],
  },
  {
    name: 'oyster',
    collateral_adjectives: [
      'ostraceous',
      'ostracean',
      'ostreaceous',
      'oysterous',
      'oystery',
    ],
  },
  {
    name: 'pachyderm',
    collateral_adjectives: ['pachydermatous'],
  },
  {
    name: 'palm-cat',
    collateral_adjectives: ['paradoxurine'],
  },
  {
    name: 'panther',
    collateral_adjectives: ['pantherine'],
  },
  {
    name: 'parrot',
    collateral_adjectives: ['parroty', 'psittacine'],
  },
  {
    name: 'partridge',
    collateral_adjectives: ['perdicine'],
  },
  {
    name: 'peafowl',
    collateral_adjectives: ['pavonine'],
  },
  {
    name: 'perch',
    collateral_adjectives: ['percine'],
  },
  {
    name: 'percher',
    collateral_adjectives: ['passerine'],
  },
  {
    name: 'phalanger',
    collateral_adjectives: ['phalangistine'],
  },
  {
    name: 'pheasant',
    collateral_adjectives: ['phasianine'],
  },
  {
    name: 'pig',
    collateral_adjectives: [
      'aprine',
      'piggy',
      'porcine',
      'suidian',
      'suilline',
      'suine',
    ],
  },
  {
    name: 'polyp',
    collateral_adjectives: ['polypine'],
  },
  {
    name: 'porcupine',
    collateral_adjectives: ['hystricine'],
  },
  {
    name: 'porpoise',
    collateral_adjectives: ['cetacean'],
  },
  {
    name: 'Portuguese man-of-war',
    collateral_adjectives: ['physalian'],
  },
  {
    name: 'primate',
    collateral_adjectives: ['primatal'],
  },
  {
    name: 'python',
    collateral_adjectives: ['pythonine'],
  },
  {
    name: 'rabbit',
    collateral_adjectives: ['leporine', 'rabbitish', 'rabbity'],
  },
  {
    name: 'rail',
    collateral_adjectives: ['ralline'],
  },
  {
    name: 'rat',
    collateral_adjectives: ['rattish', 'ratty'],
  },
  {
    name: 'rattlesnake',
    collateral_adjectives: ['crotaline'],
  },
  {
    name: 'raven',
    collateral_adjectives: ['corvine'],
  },
  {
    name: 'reindeer',
    collateral_adjectives: ['rangiferine'],
  },
  {
    name: 'reptile',
    collateral_adjectives: ['reptilian'],
  },
  {
    name: 'rhinoceros',
    collateral_adjectives: ['rhinocerotic'],
  },
  {
    name: 'rodent',
    collateral_adjectives: ['rodential', 'rodentian', 'glirine'],
  },
  {
    name: 'saki',
    collateral_adjectives: ['pithecian'],
  },
  {
    name: 'salmon',
    collateral_adjectives: ['salmonoid'],
  },
  {
    name: 'scorpion',
    collateral_adjectives: ['scorpionid'],
  },
  {
    name: 'seal',
    collateral_adjectives: ['phocine'],
  },
  {
    name: 'sea-urchin',
    collateral_adjectives: ['echinal'],
  },
  {
    name: 'sheep',
    collateral_adjectives: ['ovine', 'sheepy'],
  },
  {
    name: 'shrew',
    collateral_adjectives: ['soricine'],
  },
  {
    name: 'skink',
    collateral_adjectives: ['scincoid'],
  },
  {
    name: 'slug',
    collateral_adjectives: ['limaceous', 'limacine', 'limacoid'],
  },
  {
    name: 'snail',
    collateral_adjectives: ['limaceous', 'snaily'],
  },
  {
    name: 'snake',
    collateral_adjectives: ['anguine', 'ophidian', 'serpentine'],
  },
  {
    name: 'songbird',
    collateral_adjectives: ['oniscine', 'oscine'],
  },
  {
    name: 'spider',
    collateral_adjectives: ['arachnidan', 'araneidan'],
  },
  {
    name: 'squirrel',
    collateral_adjectives: ['sciurine', 'squirrelly'],
  },
  {
    name: 'starling',
    collateral_adjectives: ['sturnine'],
  },
  {
    name: 'swallow',
    collateral_adjectives: ['hirundine'],
  },
  {
    name: 'swan',
    collateral_adjectives: ['cycnean', 'cygnean', 'swanny'],
  },
  {
    name: 'tapeworm',
    collateral_adjectives: ['taenioid'],
  },
  {
    name: 'tarsier',
    collateral_adjectives: ['tarsioid'],
  },
  {
    name: 'termite',
    collateral_adjectives: ['termitic', 'termitine'],
  },
  {
    name: 'thrush',
    collateral_adjectives: ['turdine'],
  },
  {
    name: 'tick',
    collateral_adjectives: ['acarian', 'acarid', 'acaridan', 'acarine'],
  },
  {
    name: 'tiger',
    collateral_adjectives: ['tigerish', 'tigerly', 'tigery', 'tigrine'],
  },
  {
    name: 'tit',
    collateral_adjectives: ['parine'],
  },
  {
    name: 'toad',
    collateral_adjectives: ['toady'],
  },
  {
    name: 'torpedo',
    collateral_adjectives: ['torpedinoid'],
  },
  {
    name: 'tortoise',
    collateral_adjectives: [
      'chelonian',
      'testudinal',
      'testudinate',
      'testudinian',
    ],
  },
  {
    name: 'turtle',
    collateral_adjectives: ['chelonian'],
  },
  {
    name: 'viper',
    collateral_adjectives: ['viperine', 'viperish'],
  },
  {
    name: 'vole',
    collateral_adjectives: ['microtine'],
  },
  {
    name: 'vulture',
    collateral_adjectives: ['vulturine'],
  },
  {
    name: 'wasp',
    collateral_adjectives: ['vespine', 'waspish'],
  },
  {
    name: 'whale',
    collateral_adjectives: ['cetacean', 'whalish'],
  },
  {
    name: 'wolf',
    collateral_adjectives: ['lupine', 'wolfish', 'wolfy'],
  },
  {
    name: 'wombat',
    collateral_adjectives: ['marsupial'],
  },
  {
    name: 'woodlouse',
    collateral_adjectives: ['oniscoid'],
  },
  {
    name: 'woodpecker',
    collateral_adjectives: ['picine'],
  },
  {
    name: 'worm',
    collateral_adjectives: ['vermian', 'wormy'],
  },
  {
    name: 'zebra',
    collateral_adjectives: ['zebrine'],
  },
]

window['countries'] = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua & Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia & Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo Democratic Republic',
  'Costa Rica',
  "Cote D'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea North',
  'Korea South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar (Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian State*',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Samoa',
  'San Marino',
  'Sao Tome & Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'St. Kitts & Nevis',
  'St. Lucia',
  'St. Vincent & The Grenadines',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'The Netherlands',
  'The Philippines',
  'Togo',
  'Tonga',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States Of America',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City (Holy See)',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
]
